### ISSUE TITLE
Where's the source?

### ISSUE THREAD

**Issue by Theblockbuster1** [mihabozic123/MB-Flooder#1]
The source should be in the [Code](https://github.com/mihabozic123/MB-Flooder), and the [Releases](https://github.com/mihabozic123/MB-Flooder/releases) should include the .exe file, not the other way round (also compilation instructions in the README would be helpful).
Edit: the link to the "source code" in Releases is not a source code...

**Comment by mihabozic123** [comment]
it is closed source for now
